### ISSUE TITLE
Embeddings for (A)CE models

### ISSUE THREAD

**Issue by cortner** [ACEsuit/EquivariantModels.jl#2]
The initial prototype is a bit rigid in the class of particles systems. We need to import the very general ideas to construct embeddings from ACE.jl. 

@zhanglw0521 you are a bit familiar with that, maybe you can give @CheukHinHoJerry an introduction? But don't get started on it yet.

**Comment by zhanglw0521** [comment]
Does it mean that we need a more general `state` structure instead of merely the positions of particles?

**Comment by cortner** [comment]
Related to this - should we bring the States idea to this package?

**Comment by zhanglw0521** [comment]
I can imagine it is useful to have the `States` structure in certain cases. Basically, it should not be hard to use a state as an input of a lux chain (e.g., split the input `x` as ( (|`x.rr`|, `x.be`), \hat{`x.rr`}) in the first layer and send them to radial basis and Ylm basis, respectively, in the second layer, the rest just follows), but not sure where the `States` structure should go in (this package or the new P4ML.jl, or elsewhere?) and whether or not is it elegant to have it. 

Also, it seems that `States` is not the only thing to consider under this issue - should we discuss this in more detail at some point, say, next Tue?

**Comment by cortner** [comment]
Where did we leave the discussion about the `State`

**Comment by zhanglw0521** [comment]
We mentioned we can either have one more layer in between `EquivariantModels.jl` and real implementations to deal with the `State` or simply leave it in each implementation specified package.

**Comment by cortner** [comment]
So specifically - did we have a firm decision on keeping the `State` out of this package? Or did we say we will discuss it again? I keep coming back to it and am wondering whether what we are writing here is essentially ACE3. The best parts of `ACE.jl` should then be integrated here. And in my mind, `State` was a very successful idea.

**Comment by zhanglw0521** [comment]
No, we didn't have a firm decision on this but just saying that it is not the most urgent thing. 

And does it mean that this package will eventually serve as something like ACE3? I am somewhat for this idea, so will have totally no problem with it if we finally want `State` to lie here.

**Comment by CheukHinHoJerry** [comment]
I think it is time to discuss/iterate over this? I advocate for the `State` idea. And if we need more functionality maybe we can make it a tiny package so that `P4ML` can also depends on?

cc @cortner @zhanglw0521 @YangshuaiWang

**Comment by cortner** [comment]
We can try that. If I understand you right you want to take the `ACE.State` and put this into a separate package so we can use it from anywhere we want? Some ideas: 
- `ParticleStates.jl` 
- `AbstractParticles.jl`
- `ParticleSystems.jl` 
- `AbstractParticleSystems.jl` 

??

**Comment by CheukHinHoJerry** [comment]
What in my mind is that we have a tiny package for `States` and then write an interface for it from `P4ML` to make sure all the `rrules` work as expected even with `State` input, so that we can easily build any models from it. Not sure whether this would be ideal...

If we decide to try this I think `AbstractParticles.jl` makes sense.

**Comment by zhanglw0521** [comment]
> If we decide to try this I think `AbstractParticles.jl` makes sense.

vote for this name too

**Comment by cortner** [comment]
Ok, I’ll try to get something started tomorrow

**Comment by cortner** [comment]
I am liking `DecoratedParticles.jl` -- but we can change this later if we want.

**Comment by cortner** [comment]
closed by creation of [`DecoratedParticles.jl`](https://github.com/ACEsuit/DecoratedParticles.jl)
